/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sqteam_Main */

#ifndef _Included_org_sqteam_Main
#define _Included_org_sqteam_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sqteam_Main
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_sqteam_Main_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
