/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sqteam_VkCanvas */

#ifndef _Included_org_sqteam_VkCanvas
#define _Included_org_sqteam_VkCanvas
#ifdef __cplusplus
extern "C" {
#endif
#undef org_sqteam_VkCanvas_FOCUS_TRAVERSABLE_UNKNOWN
#define org_sqteam_VkCanvas_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef org_sqteam_VkCanvas_FOCUS_TRAVERSABLE_DEFAULT
#define org_sqteam_VkCanvas_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef org_sqteam_VkCanvas_FOCUS_TRAVERSABLE_SET
#define org_sqteam_VkCanvas_FOCUS_TRAVERSABLE_SET 2L
#undef org_sqteam_VkCanvas_TOP_ALIGNMENT
#define org_sqteam_VkCanvas_TOP_ALIGNMENT 0.0f
#undef org_sqteam_VkCanvas_CENTER_ALIGNMENT
#define org_sqteam_VkCanvas_CENTER_ALIGNMENT 0.5f
#undef org_sqteam_VkCanvas_BOTTOM_ALIGNMENT
#define org_sqteam_VkCanvas_BOTTOM_ALIGNMENT 1.0f
#undef org_sqteam_VkCanvas_LEFT_ALIGNMENT
#define org_sqteam_VkCanvas_LEFT_ALIGNMENT 0.0f
#undef org_sqteam_VkCanvas_RIGHT_ALIGNMENT
#define org_sqteam_VkCanvas_RIGHT_ALIGNMENT 1.0f
#undef org_sqteam_VkCanvas_serialVersionUID
#define org_sqteam_VkCanvas_serialVersionUID -7644114512714619750i64
#undef org_sqteam_VkCanvas_serialVersionUID
#define org_sqteam_VkCanvas_serialVersionUID -2284879212465893870i64
/*
 * Class:     org_sqteam_VkCanvas
 * Method:    paint
 * Signature: (Ljava/awt/Graphics;)V
 */
JNIEXPORT void JNICALL Java_org_sqteam_VkCanvas_paint
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
